Clear-Stuff:
  clear-inventory: false
  clear-enderchest: false
  kill-villagers: false

Give-Plastron: true

Nether:
  Nether-Close: true  # If true, Kill Guardian Of Nether for Open Nether
  Boss-Dead: false
